version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

  php:
    image: lucaswpl/alpine:php-fpm-mysql
    container_name: php
    restart: unless-stopped
    depends_on:
      - mysql
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan serve --host 0.0.0.0
    ports:
      - "80:8000"
    networks:
      - app-network

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     networks:
#       - app-network

#   node:
#     container_name: node
#     image: lucaswpl/alpine:node14-essentials
#     command: tail -f /dev/null
#     ports:
#       - '127.0.0.1:8080:8080'
#     volumes:
#       - ./:/srv/app
